% File: trainModel.m
% Define training options
options = trainingOptions('sgdm', ...
    'MiniBatchSize', 32, ...
    'MaxEpochs', 10, ...
    'InitialLearnRate', 1e-4, ...
    'ValidationData', imdsValidation, ...
    'ValidationFrequency', 30, ...
    'Verbose', false, ...
    'Plots', 'training-progress');

% Train the model
net = trainNetwork(imdsTrain, lgraph, options);


% Save trained model
save('face_mask_model.mat', 'net');  
disp('Model saved successfully as face_mask_model.mat');

